docType = "DiscountGroup"
tableComment = "discount group"

tableName ="discount_group"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="value",					type="double",	 comment="value"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{name="discount_group_title_already_exist", ext="UNIQUE (title)"}
]

triggers = [
	{name="discount_group_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="discount_group_trigger_before", when="before insert or update", ref="for each row", funcName="discount_group_trigger_before"},
	{name="discount_group_trigger_after", when="after insert or update", ref="for each row", funcName="discount_group_trigger_after"}
]



methods = [
	"discount_group_list",
	"discount_group_update",
	"discount_group_get_by_id",
	"discount_group_trigger_before",
	"discount_group_trigger_after"
]

alterScripts = [
	"alter table discount_group add column if not exists title CHARACTER VARYING(150);",
	"alter table discount_group add column if not exists value double precision;",
	"alter table discount_group add column if not exists search_text text;"
]