version: '2'
services:
  app:
    build: .
    networks:
      - rozetki_net
    depends_on:
      - postgres

  postgres:
    image: postgres:13
#    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    volumes:
      - postgres_data_Rozetki_13:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    environment:
      POSTGRES_PASSWORD: xvzDV4curLidx8IWZJ6czDHQ1qa7wjfL

volumes:
  postgres_data_Rozetki_13:

networks:
  rozetki_net:
    driver: bridge
