docType = "PriceGroup"
tableComment = "price group"

tableName ="price_group"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="factor",					type="double",	 comment="factor"},
	{name="old_id",					type="char",	size=100,	 comment="old_id"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{name="price_group_title_already_exist", ext="UNIQUE (title)"},
	{name="price_group_old_id_already_exist", ext="UNIQUE (old_id)"}
]

triggers = [
	{name="price_group_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="price_group_trigger_before", when="before insert or update", ref="for each row", funcName="price_group_trigger_before"},
	{name="price_group_trigger_after", when="after insert or update", ref="for each row", funcName="price_group_trigger_after"}
]



methods = [
	"price_group_list",
	"price_group_update",
	"price_group_get_by_id",
	"price_group_trigger_before",
	"price_group_trigger_after"
]

alterScripts = [
	"alter table price_group add column if not exists title CHARACTER VARYING(150);",
	"alter table price_group add column if not exists factor double precision;",
	"alter table price_group add column if not exists old_id CHARACTER VARYING(100);",
	"alter table price_group add column if not exists search_text text;"
]