
[postgres]
user = "postgres"
password = "xvzDV4curLidx8IWZJ6czDHQ1qa7wjfL"
dbName = "rozetki"
host = "postgres"
port = 5432
modelDir = ["./sql/model"]
viewDir = ["./sql/view"]
templateDir = ["./sql/template"]

[webServer]
enable = true
port = 3101
url = "https://example.ru"



[email]
sender = "e.letov@nl-a.ru"
password = "DctBltnGjGkfye21"
host = "smtp.mail.ru"
port = 465
senderName = "Rozetki"
isSendWithEmptySender = false








